### ISSUE TITLE
Input validation in the case of a partial update of an entity

### ISSUE THREAD

**Issue by nicolasiensen** [Shopify/upgrow#19]
Hey there,

First of all, great job documenting this comprehensive guide to scale Rails projects. I read it all and found it easy to understand while it offers a powerful approach for structuring not only Rails codebases but any web-based application really.

I have a couple of observations I'll share as issues in the project. Please let me know if you prefer to get this feedback somewhere else.

In this issue, I would like to point out that in the blog example, the `ArticleInput` used as a parameter for the method `UpdateArticleAction#perform` validates the presence of `title` and `body`. I wonder what would happen if the user wants to update only one of these properties. Should the user pass all the properties to this input, even those they don't want to change?

Perhaps we could have different input classes for creation and edition, with different validation rules.

What do you think?

**Comment by volmer** [comment]
Hi there, thanks for opening this discussion. 

In the blog example, the edit form is pre-filled with the information coming from the existing Article, so even if the user only wants to change, say, the title, the body content is sent back unchanged from the edit form. This works well for HTML pages, and it is similar to what you would find in a standard Rails scaffold.

Now if you're developing an API in which you would like to allow clients to send only a subset of params, you would need to use different validation strategies for your inputs. For example, you could have a `CreateArticleInput` that enforces the presence of all attributes, and an `UpdateArticleInput` with optional attributes according to your business rules.
