### ISSUE TITLE
Making Actions observable

### ISSUE THREAD

**Issue by nicolasiensen** [Shopify/upgrow#20]
In the [Caveats](https://upgrow.shopify.io/caveats/) page, there is a section dedicated to Complex Actions, which I totally agree are components that most likely will grow fat really fast on an average web application.

One suggestion I have to keep Actions lean is to make them observable.

The Action could maintain a list of subscribers as a class property. Every time an Action instance is executed successfully, it triggers a call on every subscriber following a prescribed interface. Perhaps we could reuse the `Result` of the Action to pass it around to its subscribers.

This way, I believe we could make the Actions extensible and add features without changing its implementation.

Things that could subscribe to action include email dispatcher, data lake events streamer, background job enqueuer (if it is not core to the business logic), and other side effects an Action should have in the system.

```ruby
email_dispatcher = EmailDispatcher.new
UpdateArticleAction.add_listener(email_dispatcher)
UpdateArticleAction.new.perform(params[:id], @input) # if successful, triggers a call on email_dispatcher
```

The Actions subscriptions should be set in the initialization of the Rails app.

Looking forward to knowing what you think.

**Comment by sergiopantoja** [comment]
Playing devil's advocate, wouldn't this cause the same sorts of issues described in the [Code Smells](https://upgrow.shopify.io/code-smells-in-rails-apps/) section for Active Record Callbacks?

> Since these callback methods are called implicitly by the framework, they can become inadvertently cumbersome. By simply reading the Active Record model's code it is very hard to reason about everything that is happening around method calls and callbacks. Similar to controller callbacks, these can also apply to subsets of methods or be conditional to certain states, which further hinders understanding the possible logic paths and makes code very hard to change and maintain.

> The very existence of callbacks in Active Record models is a smell in itself: there is no reason not to replace them with explicit, direct method calls through more thoughtful and meaningful software design.
